#!/bin/bash

# Filters lines with (when stripped) only "{" or "}" to include a blank lua comment.
# This prevents Crawl from interpreting them as the end of a lua block.
filter() {
    oldifs="$IFS"
    IFS=""
    while read line; do
        block=$(echo "$line" | tr -d '[:space:]')
        printf "%s" "$line"
        if [[ "$block" == "{" ]] || [[ "$block" == "}" ]]; then
            printf "%s" " --"
        fi
        printf "\n"
    done
    IFS="$oldifs"
}

echo "{"
# Indent file and output.
sed "s/^/    /" < "$CRC_FILE" | filter
echo "}"
